PUT http://localhost:8855/admin/adminUser/37  HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjI4LCJ1c2VyX25hbWUiOiJhZG1pbiIsImFkbWluIjp0cnVlLCJleHAiOjE2NTYzMzM3OTN9.ZjAu3ksFs-L_UbgT61rHopJD5FEWtKyR443JD_W5Hw0

{
    "user_name":"dwqadmin4",
    "pwd":"1234556",
    "email":"1234@qq.com"
}